spring.application.name=AlkemyDiego

spring.cloud.gcp.firestore.project-id=productos-alkemy-diego
spring.cloud.gcp.firestore.credentials.location=adminsdk.json

# JWT configuration
app.jwt.secret=YmFzZTY0ZW5jb2RlZGtleQ==
app.jwt.expiration=3600000